### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by alexandre1985** [mafintosh/chromecasts#38]
In my Manjaro Linux Deepin operative system I have done:
```
git clone https://github.com/mafintosh/chromecasts.git
cd chromecasts/
npm install
create a chromecast.js file with the content of the Usage file in your GitHub README.md
node chromecast.js
```
The TV with the Google Chromecast is turned on, and this is the (error) output that chromecast.js gives me
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'chromecasts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/daniel/chromecasts/chromecasts.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by alxhotel** [comment]
You need to change the require call to something like `require('./')` if you want to use the module inside it's own repo
